BAH-1256 Add a button to start ad-hoc tele-consultation in the header section in the ‘Patient Dashboard’ Screen.
Bahmni/openmrs-module-bahmniapps pull request #382
Opened 2021-10-19 06:52 UTC by vishalreddysarasani

Refer https://bahmni.atlassian.net/browse/BAH-1256

Added a button and info pop up box for ad-hoc teleconsultation changes
![Screenshot from 2021-10-04 12-18-28](https://user-images.githubusercontent.com/14124081/137859344-57779f03-8724-4001-8768-9629ebf643aa.png)

2021-11-08 09:50 UTC, gsluthra requested changes

2021-11-08 11:21 UTC, vishalreddysarasani commented on ui/app/clinical/dashboard/views/clinicalDashboardHeader.html
> +                <div ng-if="::clinicalDashboardConfig.allowAdhocTeleConsultation" ng-click="startAdhocTeleconsultationLink()" class="dialog-button-group start-tele-consultation"
Yes @gsluthra it defaults to false

2021-11-09 08:07 UTC, vishalreddysarasani commented on ui/app/clinical/consultation/controllers/consultationController.js
> +                            messagingService.showMessage('error', "{{'TELECON_ERROR_KEY' | translate }}");
Changed

2021-11-09 08:07 UTC, vishalreddysarasani commented on ui/app/clinical/consultation/controllers/consultationController.js
> +                                if (status === 1) {
Using constant

2021-11-11 09:53 UTC, gsluthra approved these changes

2022-11-01 07:02 UTC, kushboojain commented
The changes are moved to another PR and its been merged.

2022-11-01 07:02 UTC, closed without merging