BAH-3093 | Module Federation Micro-frontend Setup for IPD
Bahmni/openmrs-module-bahmniapps pull request #888
Opened 2024-03-27 11:10 UTC by tanyaa-tw

Jira Link- https://bahmni.atlassian.net/jira/software/c/projects/BAH/issues/BAH-3093?jql=project%20%3D%20%22BAH%22%20ORDER%20BY%20created%20DESC

2024-04-01 06:31 UTC, tanyaa-tw commented
We have updated the test coverage to ensure the pipeline workflow progresses without encountering any issues. As the Bahmni-IPD-Master test coverage is consistently maintained and the pipeline is functioning smoothly, the coverage adjustments made will be reverted back as part of the upcoming pull request."

2024-04-12 12:25 UTC, rahu1ramesh requested changes

2024-04-12 12:25 UTC, rahu1ramesh commented on ui/app/clinical/consultation/views/treatmentSections/drugOrderHistory.html
The changes added to this file here is for the `Print Medication` feature, which is not relevant to this PR. It would be appreciated if this could be a separate PR to allow us to track the changes more effectively, enabling both review and testing of this new feature.

2024-04-12 12:25 UTC, rahu1ramesh commented on ui/app/clinical/displaycontrols/treatmentData/views/treatmentTable.html
The changes added to this file here is for the `IPD Drug button` feature, which is not relevant to this PR. It would be appreciated if this could be a separate PR to allow us to track the changes more effectively, enabling both review and testing of this new feature.

2024-04-12 12:25 UTC, rahu1ramesh commented on ui/app/clinical/displaycontrols/treatmentData/views/treatmentTableRow.html
The changes added to this file here is for the `IPD Drug button` feature, which is not relevant to this PR. It would be appreciated if this could be a separate PR to allow us to track the changes more effectively, enabling both review and testing of this new feature.

2024-04-12 12:25 UTC, rahu1ramesh commented on ui/app/common/constants.js
The changes added to this file here is for the `Order Notes Template` feature, which is not relevant to this PR. It would be appreciated if this could be a separate PR to allow us to track the changes more effectively, enabling both review and testing of this new feature.

2024-04-12 12:25 UTC, rahu1ramesh commented on ui/app/common/patient-search/controllers/patientsListController.js
The changes added to this file here is related to the [BAH-3024](https://github.com/Bahmni/openmrs-module-bahmniapps/pull/628) feature, which is not relevant to this PR. It would be appreciated if this could be a separate PR to allow us to track the changes more effectively, enabling both review and testing of this new feature.

2024-04-12 12:25 UTC, rahu1ramesh commented on ui/app/common/patient/mappers/patientMapper.js
The changes added to this file here is for the `Print Medication` feature, which is not relevant to this PR. It would be appreciated if this could be a separate PR to allow us to track the changes more effectively, enabling both review and testing of this new feature.

2024-04-12 12:25 UTC, rahu1ramesh commented on ui/app/orders/views/orderFulfillment.html
The changes added to this file here I believe is for the `Order Notes Template` feature, which is not relevant to this PR. It would be appreciated if this could be a separate PR to allow us to track the changes more effectively, enabling both review and testing of this new feature.

2024-04-12 12:25 UTC, rahu1ramesh commented on ui/app/ot/views/listView.html
The changes added to this file here I believe is for the [BAH-3092](https://github.com/Bahmni/openmrs-module-bahmniapps/pull/903) feature, which is not relevant to this PR. It would be appreciated if this could be a separate PR to allow us to track the changes more effectively, enabling both review and testing of this new feature.

2024-04-12 12:25 UTC, rahu1ramesh commented on ui/app/styles/clinical/_patientDashboard.scss
The changes added to this file here is for the `IPD Drug button` feature, which is not relevant to this PR. It would be appreciated if this could be a separate PR to allow us to track the changes more effectively, enabling both review and testing of this new feature.

2024-04-12 12:25 UTC, rahu1ramesh commented on ui/app/common/attributeTypes/directives/attributeTypes.js
Considering that the location attribute is specific to the CURE implementation and may not be relevant to Bahmni in general, perhaps we should reconsider merging this to the main branch. 

cc: @angshu, @binduak

2024-04-12 12:30 UTC, rahu1ramesh commented
I haven't reviewed the changes made to the spec files yet. I believe it would be beneficial to break down the PR by separating the `IPD Drug`, `Order Template`, and `Print Medication` features. Additionally, it's essential to merge the PRs raised against both `BAH-3092` and `BAH-3024` into the master branch before proceeding with this PR and then rebase the changes accordingly.

2024-04-18 03:50 UTC, rahu1ramesh commented
This PR is being closed since @AshishkurianTw @tanyaa-tw have raised a new PR with the relevant changes. You can find the new PR here: #907. Thank you for your contribution!

2024-04-18 03:50 UTC, closed without merging