Bindu, Kavitha,Phani | BAH-3092 | Show primary diagnoses in OT list view
Bahmni/openmrs-module-bahmniapps pull request #903
Opened 2024-04-11 18:10 UTC by binduak

2024-04-22 11:39 UTC, rahu1ramesh requested changes
In both the OT list and print views should display only the primary diagnosis, provided the global property is not null.

2024-05-08 02:55 UTC, rahu1ramesh commented on ui/app/ot/views/listView.html
The primary diagnosis column remains visible when `obs.conceptMappingsForOT` is set, regardless of whether `additionalCustomParam` is configured. This makes it challenging for the implementer to hide the column from view.

2024-05-09 05:54 UTC, kavitha-sundararajan commented on ui/app/ot/views/listView.html
added check for the global property to show the column

2024-05-13 12:33 UTC, rahu1ramesh approved these changes

2024-05-13 13:11 UTC, merged