Arjun | BAH-3818 | Default values of program and program state
Bahmni/openmrs-module-bahmniapps pull request #941
Opened 2024-05-10 07:29 UTC by binduak

JIRA card -> [https://bahmni.atlassian.net/browse/BAH-3818](https://bahmni.atlassian.net/browse/BAH-3818)

2024-05-17 05:49 UTC, rahu1ramesh requested changes

2024-05-20 12:57 UTC, Arjun-Go commented on ui/app/common/attributeTypes/views/attributeInformation.html
> +    <div class="left" data-ng-switch-when="org.openmrs.customdatatype.datatype.ConceptDatatype">
Removed this tag

2024-05-20 12:58 UTC, Arjun-Go commented on ui/app/common/uicontrols/programmanagement/views/programRow.html
> +            <div class="form-field program-outcome-container" ng-show="patientProgram.editing && !disableProgramOutcome">
By default, in product, the programOutcome section is shown and that's the reason why the config is named `disableProgramOutcome`. This is shown in the program edit section

2024-05-21 03:09 UTC, rahu1ramesh commented
| disableProgramOutcome set to false | disableProgramOutcome set to true |
|---------------|------------------------|
|![Screenshot 2024-05-21 at 8 18 02 AM](https://github.com/Bahmni/openmrs-module-bahmniapps/assets/121226043/ce86322f-28e4-4437-a5db-99da9730354c) | ![Screenshot 2024-05-21 at 8 17 42 AM](https://github.com/Bahmni/openmrs-module-bahmniapps/assets/121226043/d2dcc44b-cd4a-4924-a87f-f2e7414bd148) |

I suggest renaming `disableProgramOutcome` as it does not disable the outcome itself but rather the option to edit it.

2024-05-21 11:24 UTC, rahu1ramesh approved these changes

2024-05-21 11:34 UTC, merged