Tanya,Kavitha | BAH-3844 | Enable IPD Feature in patient Dashboard
Bahmni/openmrs-module-bahmniapps pull request #959
Opened 2024-05-31 01:46 UTC by binduak

JIRA - https://bahmni.atlassian.net/browse/BAH-3844

2024-06-04 12:35 UTC, rahu1ramesh requested changes

2024-06-04 12:35 UTC, rahu1ramesh commented on ui/app/clinical/consultation/directives/newDrugOrders.js
> -            $scope.enableIPDFeature = appService.getAppDescriptor().getConfigValue("enableIPDFeature");
@binduak @kavitha-sundararajan I can see that `enableIPDFeature` is being replaced with `allMedicinesInPrescriptionAvailableForIPD`. Was this a conscious decision, if so can you state the rationale behind it?

2024-06-04 18:14 UTC, rahu1ramesh requested changes

2024-06-05 07:19 UTC, Arjun-Go commented on ui/app/clinical/common/services/clinicalAppConfigService.js
> +        this.getIsIPDFeatureEnabled = function () {
Looks like it's not used anywhere. can be removed

2024-06-05 07:20 UTC, Arjun-Go commented on ui/test/unit/clinical/common/controllers/visitHeaderController.spec.js
> +    var mockClinicalAppConfigService = jasmine.createSpyObj('clinicalAppConfigService', ['getConsultationBoardLink', 'getAllConsultationBoards', 'getIsIPDFeatureEnabled']);
This too can be removed

2024-06-05 07:21 UTC, Arjun-Go commented on ui/app/common/patient/header/views/header.html
This can be reverted, the change was done in one of the recent changes in Bahmni-IPD-master branch too

2024-06-05 12:16 UTC, rahu1ramesh approved these changes

2024-06-05 12:37 UTC, rahu1ramesh approved these changes

2024-06-07 04:25 UTC, merged